///////////////////////////////////////////////////////////////////////////////
// Untitled2ClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Untitled2ClassFactory.h"
#include "Untitled2Services.h"
#include "Untitled2Version.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CUntitled2ClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_Untitled2CModule1, SRVNAME_UNTITLED2 "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUntitled2ClassFactory::CUntitled2ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_UNTITLED2)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Untitled2));
#endif //defined(TCDBG_UNIT_VERSION)
}

