///////////////////////////////////////////////////////////////////////////////
// Untitled2Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled2 = 0x3F000000;
#define SRVNAME_UNTITLED2 "Untitled2"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled2CModule1 = {0x3b77d30e,0x9504,0x4b63,{0xab,0x64,0x88,0x69,0xad,0x16,0x43,0xae}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
