///////////////////////////////////////////////////////////////////////////////
// Untitled2Interfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "Untitled2Services.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
