<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="WAIT" Id="{a19271ea-9d31-488e-bd01-3f15a97a4b2e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK  WAIT

VAR_INPUT
	TIME_IN   :TIME;
END_VAR

VAR_OUTPUT
	OK        :BOOL:=FALSE;
END_VAR

VAR
	ZAB       :TP;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Il"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"LD"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB.Q"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">11L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">10L</v>
                    </o>
                    <o>
                      <v n="Operator">"JMPC"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"mark"</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">19L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">18L</v>
                    </o>
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">21L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">20L</v>
                    </o>
                    <o>
                      <v n="Operator">"CAL"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB"</v>
                        <v n="Type">"TP"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">39L</v>
                      </o>
                      <v n="Postfix">"("</v>
                      <v n="Id">38L</v>
                    </o>
                    <o>
                      <v n="Operator">"IN"</v>
                      <v n="Prefix">":="</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"FALSE"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">74L</v>
                      </o>
                      <v n="Postfix">")"</v>
                      <v n="Id">73L</v>
                    </o>
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">76L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">75L</v>
                    </o>
                    <o>
                      <v n="Operator">"LD"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"TIME_IN"</v>
                        <v n="Type">"TIME"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">43L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">42L</v>
                    </o>
                    <o>
                      <v n="Operator">"ST"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB.PT"</v>
                        <v n="Type">"TIME"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">41L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">40L</v>
                    </o>
                    <o>
                      <v n="Operator">"CAL"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB"</v>
                        <v n="Type">"TP"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">47L</v>
                      </o>
                      <v n="Postfix">"("</v>
                      <v n="Id">46L</v>
                    </o>
                    <o>
                      <v n="Operator">"IN"</v>
                      <v n="Prefix">":="</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"TRUE"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">78L</v>
                      </o>
                      <v n="Postfix">")"</v>
                      <v n="Id">77L</v>
                    </o>
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">80L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">79L</v>
                    </o>
                    <o>
                      <v n="Operator">"JMP"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"end"</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">45L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">44L</v>
                    </o>
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">37L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">36L</v>
                    </o>
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">27L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">26L</v>
                    </o>
                    <o>
                      <v n="Operator">"LDN"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB.Q"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">31L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">30L</v>
                    </o>
                    <o>
                      <v n="Operator">"ST"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"OK"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">33L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">32L</v>
                    </o>
                    <o>
                      <v n="Operator">"RET"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">35L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">34L</v>
                    </o>
                  </l2>
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems">
                    <o t="BoxTreeAssign">
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"mark"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">4</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">19L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"ZAB.Q"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">95L</v>
                        </o>
                        <v n="Id">94L</v>
                      </o>
                      <v n="Id">96L</v>
                    </o>
                    <o t="BoxTreeBox">
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="BoxType">"TP"</v>
                      <o n="Instance" t="Operand">
                        <v n="Operand">"ZAB"</v>
                        <v n="Type">"TP"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">47L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">98L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">99L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">101L</v>
                          </o>
                          <v n="Id">100L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TIME_IN"</v>
                            <v n="Type">"TIME"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">103L</v>
                          </o>
                          <v n="Id">102L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>IN</v>
                          <v>PT</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                          <v>TIME</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>Q</v>
                          <v>ET</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                          <v>TIME</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">FunctionBlock</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="Id">97L</v>
                    </o>
                    <o t="BoxTreeAssign">
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"end"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">4</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">45L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"TRUE"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">105L</v>
                        </o>
                        <v n="Id">104L</v>
                      </o>
                      <v n="Id">106L</v>
                    </o>
                    <o t="BoxTreeAssign">
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"OK"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">33L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="BoxType">"TP"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"ZAB"</v>
                          <v n="Type">"TP"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">39L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Extensible">false</v>
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">108L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">1</v>
                          <v n="Fixed">true</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"FALSE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Extensible">false</v>
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">110L</v>
                            </o>
                            <v n="Id">109L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Extensible">false</v>
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">112L</v>
                            </o>
                            <v n="Id">111L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>IN</v>
                            <v>PT</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                            <v>ET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="Id">107L</v>
                      </o>
                      <v n="Id">113L</v>
                    </o>
                    <o t="BoxTreeAssign">
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">8</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">35L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"TRUE"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">115L</v>
                        </o>
                        <v n="Id">114L</v>
                      </o>
                      <v n="Id">116L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">9L</v>
                </o>
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"CAL"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB"</v>
                        <v n="Type">"TP"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">52L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">51L</v>
                    </o>
                  </l2>
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">"mark"</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="BoxType">"TP"</v>
                      <o n="Instance" t="Operand">
                        <v n="Operand">"ZAB"</v>
                        <v n="Type">"TP"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">52L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">118L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">119L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">121L</v>
                          </o>
                          <v n="Id">120L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">123L</v>
                          </o>
                          <v n="Id">122L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>IN</v>
                          <v>PT</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                          <v>TIME</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>Q</v>
                          <v>ET</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                          <v>TIME</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">FunctionBlock</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="Id">117L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">50L</v>
                </o>
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"LDN"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"ZAB.Q"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">55L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">54L</v>
                    </o>
                    <o>
                      <v n="Operator">"ST"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"OK"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">57L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">56L</v>
                    </o>
                    <o>
                      <v n="Operator">"RET"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Extensible">false</v>
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">59L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">58L</v>
                    </o>
                  </l2>
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">"end"</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"OK"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">57L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"ZAB.Q"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">1</v>
                            <v n="Fixed">true</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">125L</v>
                        </o>
                        <v n="Id">124L</v>
                      </o>
                      <v n="Id">126L</v>
                    </o>
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">""</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Extensible">false</v>
                              <v n="Flags">8</v>
                              <v n="Fixed">true</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">59L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Extensible">false</v>
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"TRUE"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Extensible">false</v>
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">128L</v>
                        </o>
                        <v n="Id">127L</v>
                      </o>
                      <v n="Id">129L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">53L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="ILStatement">{6a53a656-0ed2-439d-9798-f11da86e9f5e}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>